# Generated by Django 3.2 on 2023-07-02 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_appointment_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='pre_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_pre_assessment', to='management.pre_assessment'),
        ),
    ]
