# Generated by Django 3.2 on 2023-07-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_appointment_pre_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
