# Generated by Django 3.2 on 2023-07-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='doctor_type',
            field=models.CharField(blank=True, choices=[('Cardiologist', 'Cardiologist'), ('Neurologist', 'Neurologist'), ('Radiologist', 'Radiologist'), ('Surgeon', 'Surgeon'), ('Pediatrician', 'Pediatrician'), ('Dermatologist', 'Dermatologist')], max_length=255, null=True),
        ),
    ]
